// Mock knowledge base: 15 departments the router can send a grievance to.
// In a real deployment this comes from the CPGRAMS org directory and is kept
// current by the freshness pipeline (see /admin).

export const KB_VERSION = "1.2";

export const DEPARTMENTS = [
  {
    id: "municipal",
    ministry: "Ministry of Housing and Urban Affairs",
    department: "Urban Local Body (Nagar Nigam / Municipality)",
    scope: "City water supply, garbage collection, drainage, streetlights, local roads, stray animals, encroachment",
    keywords: ["water", "paani", "garbage", "kachra", "drain", "naali", "streetlight", "pothole", "sadak", "sewage", "municipal"],
    level: "municipal",
  },
  {
    id: "jalshakti",
    ministry: "Ministry of Jal Shakti",
    department: "Department of Drinking Water and Sanitation / State Jal Nigam",
    scope: "Rural drinking water schemes, Jal Jeevan Mission connections, hand pumps, water quality",
    keywords: ["jal", "drinking water", "hand pump", "jal jeevan", "water quality", "village water"],
    level: "state",
  },
  {
    id: "morth",
    ministry: "Ministry of Road Transport and Highways",
    department: "NHAI / Regional Office",
    scope: "National highways: potholes, tolls, signage, service roads",
    keywords: ["highway", "nh", "toll", "national highway"],
    level: "central",
  },
  {
    id: "railways",
    ministry: "Ministry of Railways",
    department: "Zonal Railway / IRCTC",
    scope: "Train delays, refunds (TDR), cleanliness, tatkal issues, station facilities",
    keywords: ["train", "railway", "irctc", "refund", "tatkal", "station", "tdr"],
    level: "central",
  },
  {
    id: "dfs",
    ministry: "Ministry of Finance",
    department: "Department of Financial Services",
    scope: "Public sector banks, ATM disputes, loan harassment, insurance (LIC), pension accounts in banks",
    keywords: ["bank", "atm", "loan", "insurance", "lic", "account", "kyc"],
    level: "central",
  },
  {
    id: "epfo",
    ministry: "Ministry of Labour and Employment",
    department: "Employees' Provident Fund Organisation (EPFO)",
    scope: "PF withdrawal claims, transfer, KYC mismatch, pension under EPS-95, employer not depositing PF",
    keywords: ["pf", "epf", "provident", "epfo", "uan", "eps"],
    level: "central",
  },
  {
    id: "doppw",
    ministry: "Ministry of Personnel, Public Grievances and Pensions",
    department: "Department of Pension and Pensioners' Welfare",
    scope: "Central government pension delays, family pension, life certificate issues",
    keywords: ["pension", "pensioner", "family pension", "life certificate"],
    level: "central",
  },
  {
    id: "health",
    ministry: "Ministry of Health and Family Welfare",
    department: "State Health Department / CGHS",
    scope: "Government hospital negligence, CGHS card issues, Ayushman Bharat empanelment",
    keywords: ["hospital", "doctor", "cghs", "ayushman", "medicine", "clinic"],
    level: "state",
  },
  {
    id: "education",
    ministry: "Ministry of Education",
    department: "Department of School Education / Scholarship Division",
    scope: "Scholarship not credited, school infrastructure, fee disputes in govt institutions",
    keywords: ["scholarship", "school", "college", "fees", "exam"],
    level: "central",
  },
  {
    id: "consumer",
    ministry: "Ministry of Consumer Affairs, Food and Public Distribution",
    department: "Department of Consumer Affairs / Ration (PDS)",
    scope: "Ration card issues, PDS dealer complaints, overcharging, weights and measures",
    keywords: ["ration", "pds", "consumer", "overcharging", "shopkeeper"],
    level: "state",
  },
  {
    id: "power",
    ministry: "Ministry of Power",
    department: "State Electricity Distribution Company (DISCOM)",
    scope: "Power cuts, wrong electricity bills, new connection delays, transformer faults",
    keywords: ["electricity", "bijli", "power cut", "bill", "transformer", "meter"],
    level: "state",
  },
  {
    id: "posts",
    ministry: "Ministry of Communications",
    department: "Department of Posts / DoT",
    scope: "Undelivered post, postal savings issues, mobile network complaints (via TRAI)",
    keywords: ["post", "parcel", "speed post", "sim", "network", "telecom"],
    level: "central",
  },
  {
    id: "police",
    ministry: "Ministry of Home Affairs",
    department: "State Police (via State Grievance Cell)",
    scope: "FIR not registered, police inaction (non-urgent; emergencies go to 112)",
    keywords: ["police", "fir", "thana", "chowki"],
    level: "state",
  },
  {
    id: "petroleum",
    ministry: "Ministry of Petroleum and Natural Gas",
    department: "Oil Marketing Company (LPG Distributor)",
    scope: "LPG cylinder delivery delays, subsidy not credited, distributor overcharging",
    keywords: ["gas", "lpg", "cylinder", "subsidy", "indane", "bharat gas"],
    level: "central",
  },
  {
    id: "passport",
    ministry: "Ministry of External Affairs",
    department: "Passport Seva / Regional Passport Office",
    scope: "Passport application stuck, police verification delays, appointment issues",
    keywords: ["passport", "psk", "police verification"],
    level: "central",
  },
];

export const EXCLUDED_CATEGORIES = [
  "RTI matters (file at rtionline.gov.in instead)",
  "Court cases / sub judice matters",
  "Religious matters",
  "Personal or family disputes",
  "Service matters of government employees (use departmental channels)",
  "Suggestions without a specific grievance",
];
